### PR TITLE
Improve path getting

### LINKED ISSUE #2: FileNotFoundError When Custom Addon Directory Not Set
Traceback edited to remove my username:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\%USER%\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RADarr-master\__init__.py", line 1883, in <module>
    class RADARR_PF_pref(AddonPreferences):
  File "C:\Users\%USER%\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RADarr-master\__init__.py", line 1892, in RADARR_PF_pref
    default=modal_state_fn(),
  File "C:\Users\%USER%\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RADarr-master\__init__.py", line 877, in modal_state_fn
    with open(modal_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '\\addons\\RADarr/modal/bool_state.txt'
```

### PR DESCRIPTION
**Pull request by Craulback**
Made getting the scripts folder path more dynamic & flexible
Tested on Windows and Linux in Blender 3.2.2

closes #2

### CODE REVIEW

**Comment by Craulback** [comment]
Closes #2

**Review by Craulback — COMMENTED** [review]
Decided to simplify it a bit and just search for RADarr in all possible paths

**Comment by arindam-m** [comment]
Hello @Craulback 

Thanks for contributing to this.

I never anticipated someone **would**, it was mainly made for the 2.8x series when there were no such add-ons available for such a specific purpose at the time.
It was also one of my earlier 'experimentations' with Python, while I was still learning a lot about the language in those days. 

Your changes are clever, clean, and with a lot less code.
And all these will be merged into the main branch soon.
However, I will be leaving a few comments on the parts you have committed to and making it even smarter.

**Comment by Craulback** [comment]
Hello @arindam-m 
You're welcome, & thanks for the kind words.
I'm pretty new to coding in general & even newer to Blender, this was actually the first addon with this type of function I found.
So when I saw the error I was just excited that I might be able to solve it. 😆

I appreciate the feedback & I look forward to reading those comments.

**Pull request merged**
